//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Harurow.Extensions.One.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Harurow.Extensions.One.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Type names should be all uppercase. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalyzerDescription {
            get {
                return ResourceManager.GetString("AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type name &apos;{0}&apos; contains lowercase letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type name contains lowercase letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AnalyzerTitle {
            get {
                return ResourceManager.GetString("AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不要な空白を削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEOCF001CodeFix {
            get {
                return ResourceManager.GetString("HEOCF001CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不要な空白があります に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEOCF001Description {
            get {
                return ResourceManager.GetString("HEOCF001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不要な空白が含まれています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEOCF001MessageFormat {
            get {
                return ResourceManager.GetString("HEOCF001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不要な空白 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEOCF001Title {
            get {
                return ResourceManager.GetString("HEOCF001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改行コードを修正 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEOCF002CodeFix {
            get {
                return ResourceManager.GetString("HEOCF002CodeFix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改行コードが混在しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEOCF002Description {
            get {
                return ResourceManager.GetString("HEOCF002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改行コードが混在しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEOCF002MessageFormat {
            get {
                return ResourceManager.GetString("HEOCF002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   改行コードの混在 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HEOCF002Title {
            get {
                return ResourceManager.GetString("HEOCF002Title", resourceCulture);
            }
        }
    }
}
